name: Actualizar Glucosa TFG

on:
  schedule:
    # Se ejecuta automáticamente cada 15 minutos en la nube
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite forzar la ejecución manual desde la web cuando quieras

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías necesarias
        run: pip install pydexcom

      - name: Ejecutar captura de glucosa
        env:
          DEXCOM_USER: ${{ secrets.DEXCOM_USER }}
          DEXCOM_PASS: ${{ secrets.DEXCOM_PASS }}
        run: python script_captura.py

      - name: Guardar cambios en el CSV del repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-actualización de datos de glucosa [skip ci]"
          file_pattern: "historial_y_directo.csv"

          
